// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlagVO1Yr7f8t2MY8hNYsru4iykgxljnI',
    appId: '1:306923043995:android:4b8f71afd1a084822e1a3e',
    messagingSenderId: '306923043995',
    projectId: 'messenger-sample-890c3',
    storageBucket: 'messenger-sample-890c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBREmSZlYl2sdEqHr_kevdtng8Is4QQY',
    appId: '1:306923043995:ios:5c3a7b49d5982b5b2e1a3e',
    messagingSenderId: '306923043995',
    projectId: 'messenger-sample-890c3',
    storageBucket: 'messenger-sample-890c3.appspot.com',
    iosClientId: '306923043995-7aeicvhi54vbvlosu27vkio4140k5kfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBREmSZlYl2sdEqHr_kevdtng8Is4QQY',
    appId: '1:306923043995:ios:5c3a7b49d5982b5b2e1a3e',
    messagingSenderId: '306923043995',
    projectId: 'messenger-sample-890c3',
    storageBucket: 'messenger-sample-890c3.appspot.com',
    iosClientId: '306923043995-7aeicvhi54vbvlosu27vkio4140k5kfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerSample',
  );
}
